#开发环境
server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10
#日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  path: D:/chatgpt-api/log
# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_4ca0d3149f21
    appid: wx26aa73f6954748fe
    token: jingtao8a

#线程池配置
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 100
      name_prefix: async-service-
      keep_alive_seconds: 100
#ChatGLM SDK Config
chatglm:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enable: false
      # 官网地址
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://open.bigmodel.cn/usercenter/apikeys
      api-secret-key: 37b5e188bca26dcc4535afc4f91c1132.nk9J7UV04PuFQz8v
